// ========== START - customize some properties by user =========
var idCustomer = null;
var idDealer = null;
var selectedPropertyValuesEcowood = '{"property_field":"18","property_value_ids":["188","147","6"]}';
// var selectedPropertyValuesEcowoodShutterColours = "{\"property_field\":\"18\",\"property_value_ids\":[\"188\", \"6\"]}";

idCustomer = jQuery('input[name="customer_id"]').val();
idDealer = jQuery('input[name="dealer_id"]').val();

// "selected_property_values": "{\"property_field\":\"18\",\"property_value_ids\":[\"188\"]}",
if (idCustomer == 274 || idDealer == 274) {
  selectedPropertyValuesEcowood = '{"property_field":"18","property_value_ids":["188","147","6"]}';
}
console.log('idCustomer ', idCustomer);
console.log('selectedPropertyValuesEcowood ', selectedPropertyValuesEcowood);
// ========== END - customize some properties by user =========

// showBiowood / showBasswood - conditional materials based on dealer visibility
var showBiowood = {};
if (typeof my_showBiowood_object !== 'undefined' && my_showBiowood_object.showBiowood === 'yes') {
  showBiowood = {
    id: 6,
    property_id: 18,
    value: 'Biowood',
    code: 'paulownia',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  };
}

var showBasswood = {};
if (typeof my_showBiowood_object !== 'undefined' && my_showBiowood_object.showBasswood === 'yes') {
  showBasswood = {
    id: 147,
    property_id: 18,
    value: 'Basswood',
    code: 'basswood',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  };
}

var names = [
  { id: 78, part_number: 'aluminum-fullheight' },
  { id: 63, part_number: 'basswood-bay' },
  { id: 64, part_number: 'basswood-bay-tot' },
  { id: 67, part_number: 'basswood-cafe' },
  { id: 95, part_number: 'basswood-cafe-bay' },
  { id: 66, part_number: 'basswood-fullheight' },
  { id: 92, part_number: 'basswood-individualshutter' },
  { id: 62, part_number: 'basswood-shaped' },
  { id: 60, part_number: 'basswood-specialshape' },
  { id: 61, part_number: 'basswood-tracked' },
  { id: 3, part_number: 'PAULOWNIA' },
  { id: 44, part_number: 'paulownia-bay' },
  { id: 51, part_number: 'paulownia-bay-tot' },
  { id: 41, part_number: 'paulownia-cafe' },
  { id: 97, part_number: 'paulownia-cafe-bay' },
  { id: 90, part_number: 'paulownia-individualshutter' },
  { id: 45, part_number: 'paulownia-specialshape' },
  { id: 106, part_number: 'paulownia-shaped' },
  { id: 94, part_number: 'paulownia-solid-flat' },
  { id: 102, part_number: 'paulownia-solid-flat-tot' },
  { id: 93, part_number: 'paulownia-solid-raised' },
  { id: 98, part_number: 'paulownia-solid-raised-cafe-style' },
  { id: 103, part_number: 'paulownia-solid-raised-tot' },
  { id: 43 },
  { id: 46, part_number: 'paulownia-tracked' },
  { id: 84, part_number: 'blackout-basswood-bay' },
  { id: 83, part_number: 'blackout-basswood-bay-tot' },
  { id: 74, part_number: 'blackout-basswood-fullheight' },
  { id: 75, part_number: 'blackout-basswood-tot' },
  { id: 82, part_number: 'blackout-paulownia-bay' },
  { id: 81, part_number: 'blackout-paulownia-bay-tot' },
  { id: 76, part_number: 'blackout-paulownia-fullheight' },
  { id: 77, part_number: 'blackout-paulownia-tot' },
  { id: 107, part_number: 'upvc-uk-fullheight' },
  { id: 55, part_number: 'upvc-bay' },
  { id: 59, part_number: 'upvc-cafe' },
  { id: 96, part_number: 'upvc-cafe-bay' },
  { id: 58, part_number: 'upvc-fullheight' },
  { id: 91, part_number: 'upvc-individualshutter' },
  { id: 52, part_number: 'upvc-specialshape' },
  { id: 57, part_number: 'upvc-tot' },
  { id: 53, part_number: 'upvc-tracked' },
  { id: 4, part_number: 'UPVC Waterproof' },
];

var property_values = [
  {
    id: 165,
    property_id: 8,
    value: '114.3mm',
    code: '114.3mm',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["188","139","147","137","5","187","138","6"]}',
    image_file_name: null,
  },
  {
    id: 55,
    property_id: 8,
    value: '88.9mm',
    code: null,
    all_products: true,
    selected_products: null,
    all_property_values: true,
    selected_property_values: null,
    image_file_name: null,
  },
  {
    id: 52,
    property_id: 8,
    value: '81.2mm Flat Louver',
    code: 'Flat Louver',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 54,
    property_id: 8,
    value: '76.2mm',
    code: '76.2mm',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","188","292"]}',
    image_file_name: null,
  },
  {
    id: 53,
    property_id: 8,
    value: '63.5mm',
    code: '63.5mm',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","187","188"]}',
    image_file_name: null,
  },
  {
    id: 164,
    property_id: 8,
    value: '50.8mm',
    code: '50.8mm',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 57,
    property_id: 9,
    value: 'Outside',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"7","property_value_ids":["32","218","146","30","225","29","33","34","42","43","221","229","227","226","222","228","230","231","232","233","31","35","36","37"]}',
    image_file_name: null,
  },
  {
    id: 56,
    property_id: 9,
    value: 'Inside',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"7","property_value_ids":["32","218","146","30","225","29","33","34","42","43","221","229","227","226","222","228","230","231","232","233","31","35","37"]}',
    image_file_name: null,
  },
  {
    id: 58,
    property_id: 9,
    value: 'Surface',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"7","property_value_ids":["33","34"]}',
    image_file_name: null,
  },
  {
    id: 151,
    property_id: 14,
    value: 'M Track',
    code: 'M',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["144"]}',
    image_file_name: null,
  },
  {
    id: 86,
    property_id: 14,
    value: 'No',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","61","307","291","323","62","310","313","420","318","319","462","321","216","322","352","353","59","300","305","320","305","320","173","141","60","306","308","311","150","309","312","63","217","67","326","66","315","316","317","329","64","314","325","328","140","65","301","302","303","324","327","330","331","332","351","333","289"]}',
    image_file_name: null,
  },
  {
    id: 89,
    property_id: 14,
    value: 'None',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["143","144"]}',
    image_file_name: null,
  },
  {
    id: 87,
    property_id: 14,
    value: 'Sill',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","67","326","66","315","316","317","329","64","314","325","328","140","65","301","302","303","324","327","352","289","420"]}',
    image_file_name: null,
  },
  {
    id: 136,
    property_id: 14,
    value: 'Track in Board',
    code: 'B',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["143"]}',
    image_file_name: null,
  },
  {
    id: 85,
    property_id: 14,
    value: 'Yes',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","307","291","323","310","313","420","318","319","462","321","322","352","353","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","333","289"]}',
    image_file_name: null,
  },
  {
    id: 71,
    property_id: 11,
    value: 'No',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","307","291","323","310","313","420","318","319","462","321","322","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","352","353","333","289"]}',
    image_file_name: null,
  },
  {
    id: 74,
    property_id: 11,
    value: 'None',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["143","144"]}',
    image_file_name: null,
  },
  {
    id: 72,
    property_id: 11,
    value: 'Sill',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","67","326","66","315","316","317","329","64","314","325","328","140","65","301","302","303","324","327","352","289","420"]}',
    image_file_name: null,
  },
  {
    id: 70,
    property_id: 11,
    value: 'Yes',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["143","144","142","291","307","323","310","313","420","318","319","462","321","322","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","352","353","333","289"]}',
    image_file_name: null,
  },
  {
    id: 76,
    property_id: 12,
    value: 'No',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","307","291","323","310","313","420","318","319","462","321","322","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","352","353","333","289"]}',
    image_file_name: null,
  },
  {
    id: 79,
    property_id: 12,
    value: 'None',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["143","144"]}',
    image_file_name: null,
  },
  {
    id: 77,
    property_id: 12,
    value: 'Sill',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","67","326","66","315","316","317","329","64","314","325","328","140","65","301","302","303","324","327","352","289","420"]}',
    image_file_name: null,
  },
  {
    id: 75,
    property_id: 12,
    value: 'Yes',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["143","144","142","291","307","323","310","313","420","318","319","462","321","322","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","352","353","333","289"]}',
    image_file_name: null,
  },
  {
    id: 81,
    property_id: 13,
    value: 'No',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","307","291","323","310","313","420","318","319","462","321","322","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","352","353","333","289"]}',
    image_file_name: null,
  },
  {
    id: 84,
    property_id: 13,
    value: 'None',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["143","144"]}',
    image_file_name: null,
  },
  {
    id: 82,
    property_id: 13,
    value: 'Sill',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["142","67","326","66","315","316","317","329","64","314","325","328","140","65","301","302","303","324","327","352","289","420"]}',
    image_file_name: null,
  },
  {
    id: 135,
    property_id: 13,
    value: 'Top Track',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"10","property_value_ids":["144"]}',
    image_file_name: null,
  },
  {
    id: 80,
    property_id: 13,
    value: 'Yes',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values:
      '{"property_field":"10","property_value_ids":["143","144","142","291","307","323","310","313","420","318","319","462","321","322","300","303","305","320","306","308","311","309","312","326","315","316","317","329","314","325","328","301","302","324","327","330","331","332","351","352","353","333","289"]}',
    image_file_name: null,
  },
  {
    id: 144,
    property_id: 10,
    value: 'Bottom M Track',
    code: 'L50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"7","property_value_ids":["37","35","187","139","147","138","6","137","5","38","39","40","41"]}',
    image_file_name: 'Bottom_M_Track.png',
  },
  {
    id: 61,
    property_id: 10,
    value: 'F50',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: 'F50.jpg',
  },
  {
    id: 62,
    property_id: 10,
    value: 'F70',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: 'F70.jpg',
  },
  {
    id: 216,
    property_id: 10,
    value: 'F90',
    code: 'F90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6"]}',
    image_file_name: 'F90_square.png',
  },
  {
    id: 59,
    property_id: 10,
    value: 'L50',
    code: 'L50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","292"]}',
    image_file_name: 'L50.jpg',
  },
  {
    id: 173,
    property_id: 10,
    value: 'G',
    code: 'L50MF',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: 'l50mf.jpg',
  },
  {
    id: 141,
    property_id: 10,
    value: 'H',
    code: 'L60SF',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: 'L60-SF.jpg',
  },
  {
    id: 60,
    property_id: 10,
    value: 'I',
    code: 'L70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147"]}',
    image_file_name: 'L70.jpg',
  },
  {
    id: 150,
    property_id: 10,
    value: 'J',
    code: 'L90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: 'L90.jpg',
  },
  {
    id: 63,
    property_id: 10,
    value: 'SBS 50',
    code: 'SBS50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6"]}',
    image_file_name: 'SBS-50.jpg',
  },
  {
    id: 143,
    property_id: 10,
    value: 'Track in Board',
    code: 'L50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"7","property_value_ids":["35","37","187","139","147","138","6","137","5","38","39","40","41"]}',
    image_file_name: 'Track_in_Board.png',
  },
  {
    id: 67,
    property_id: 10,
    value: 'Z2BS',
    code: 'Z2BS',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: 'Z2BS.jpg',
  },
  {
    id: 66,
    property_id: 10,
    value: 'Z3CS',
    code: 'Z3CS',
    all_products: true,
    selected_products: '{"product_ids":["2","3","4"]}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: 'Z3CS.jpg',
  },
  {
    id: 64,
    property_id: 10,
    value: 'Z40',
    code: 'Z40',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: 'Z40.jpg',
  },
  {
    id: 140,
    property_id: 10,
    value: 'Z40SF',
    code: 'Z40SF',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6"]}',
    image_file_name: 'Z40-SF.jpg',
  },
  {
    id: 65,
    property_id: 10,
    value: 'Z50',
    code: 'Z50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","292"]}',
    image_file_name: 'Z50.jpg',
  },
  {
    id: 90,
    property_id: 15,
    value: 'White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","139","147","187","188"]}',
    image_file_name: null,
  },
  {
    id: 464,
    property_id: 15,
    value: 'Silk White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","139","147","188"]}',
    image_file_name: null,
  },
  {
    id: 440,
    property_id: 15,
    value: 'Black',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","187","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 167,
    property_id: 15,
    value: 'Pearl',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 174,
    property_id: 15,
    value: 'Bisque',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 92,
    property_id: 15,
    value: 'Antique Brass',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 91,
    property_id: 15,
    value: 'Brass',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 168,
    property_id: 15,
    value: 'Brushed Nickel',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 117,
    property_id: 17,
    value: 'LS 032 SEA MIST',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 93,
    property_id: 15,
    value: 'Stainless Steel (+10%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  {
    id: 180,
    property_id: 15,
    value: 'Security S/S Hinge (+10%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":18,"property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 188,
    property_id: 18,
    value: 'Ecowood',
    code: 'ecowood',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  {
    id: 5,
    property_id: 18,
    value: 'Ecowood Plus',
    code: 'ecowoodPlus',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  showBiowood,
  {
    id: 138,
    property_id: 18,
    value: 'Biowood Plus',
    code: 'paulownia',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  showBasswood,
  {
    id: 139,
    property_id: 18,
    value: 'Basswood Plus',
    code: 'basswood',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  {
    id: 187,
    property_id: 18,
    value: 'Earth',
    code: 'aluminum',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  {
    id: 172,
    property_id: 15,
    value: 'Sea Mist',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","139","147","187","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 186,
    property_id: 15,
    value: 'Hidden',
    code: 'hidden',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["292","138","6","139","147","188","137","5"]}',
    image_file_name: null,
  },
  {
    id: 170,
    property_id: 20,
    value: 'No',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 169,
    property_id: 20,
    value: 'Yes',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 27,
    property_id: 7,
    value: 'ALU Panel Only',
    code: 'fullheight',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: 'alu-panel-only.png',
  },
  {
    id: 28,
    property_id: 7,
    value: 'ALU Fixed Shutter',
    code: 'fullheight',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: 'alu-fixed-shutter.png',
  },
  {
    id: 29,
    property_id: 7,
    value: 'Full Height',
    code: 'fullheight',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: 'Full_Height.png',
  },
  {
    id: 94,
    property_id: 6,
    value: 'Other',
    code: 'other',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: true,
    selected_property_values: '{"property_field":null,"property_value_ids":null}',
    image_file_name: null,
  },
  {
    id: 145,
    property_id: 17,
    value: 'Other',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 411,
    property_id: 17,
    value: 'Frosted White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["188","147","6"]}',
    image_file_name: null,
  },
  {
    id: 463,
    property_id: 17,
    value: 'Warm White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["188","147","6"]}',
    image_file_name: null,
  },
  {
    id: 412,
    property_id: 17,
    value: 'Neutral White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["188","147","6"]}',
    image_file_name: null,
  },
  {
    id: 415,
    property_id: 17,
    value: 'Shell White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["188","147","6"]}',
    image_file_name: null,
  },
  {
    id: 414,
    property_id: 17,
    value: 'Vanilla',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["188","147","6"]}',
    image_file_name: null,
  },
  {
    id: 101,
    property_id: 17,
    value: 'LS 601 PURE WHITE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 103,
    property_id: 17,
    value: 'LS 003 SILK WHITE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 104,
    property_id: 17,
    value: 'LS 630 MOST WHITE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 105,
    property_id: 17,
    value: 'LS 637 HOG BRISTLE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 106,
    property_id: 17,
    value: 'LS 609 CHAMPAGNE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 107,
    property_id: 17,
    value: 'LS 105 PEARL',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 108,
    property_id: 17,
    value: 'LS 618 ALABASTER',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 109,
    property_id: 17,
    value: 'LS 619 CREAMY',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 110,
    property_id: 17,
    value: 'LS 632 MISTRA',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 111,
    property_id: 17,
    value: 'LS 910 JET BLACK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","139"]}',
    image_file_name: null,
  },
  {
    id: 112,
    property_id: 17,
    value: 'LS 615 CLASSICAL WHITE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 113,
    property_id: 17,
    value: 'LS 617 New EGGSHELL',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 114,
    property_id: 17,
    value: 'LS 620 LIME WHITE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 115,
    property_id: 17,
    value: 'LS 621 SAND',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 116,
    property_id: 17,
    value: 'LS 622 STONE',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 118,
    property_id: 17,
    value: 'LS 049 STONE GREY',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 119,
    property_id: 17,
    value: 'LS 051 BROWN GREY',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 120,
    property_id: 17,
    value: 'LS 053 CLAY',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 121,
    property_id: 17,
    value: 'LS 072 MATTINGLEY 267',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: null,
  },
  {
    id: 122,
    property_id: 17,
    value: 'LS 108 RUSTIC GREY (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 123,
    property_id: 17,
    value: 'LS 109 WEATHERED TEAK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 124,
    property_id: 17,
    value: 'LS 110 CHIQUE WHITE (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 125,
    property_id: 17,
    value: 'LS 114 TAUPE (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 126,
    property_id: 17,
    value: 'LS 202 GOLDEN OAK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 127,
    property_id: 17,
    value: 'LS 204 OAK MANTEL (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 128,
    property_id: 17,
    value: 'LS 205 GOLDENROD (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 129,
    property_id: 17,
    value: 'LS 211 CHERRY (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 130,
    property_id: 17,
    value: 'LS 212 DARK TEAK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 131,
    property_id: 17,
    value: 'LS 214 COCOA (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 132,
    property_id: 17,
    value: 'LS 215 CORDOVAN (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 133,
    property_id: 17,
    value: 'LS 219 MAHOGANY (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 134,
    property_id: 17,
    value: 'LS 220 NEW EBONY (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 166,
    property_id: 17,
    value: 'LS 221 BLACK WALNUT (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 220,
    property_id: 17,
    value: 'LS 227 RED OAK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 253,
    property_id: 17,
    value: 'LS 229 RICH WALNUT (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 254,
    property_id: 17,
    value: 'LS 230 OLD TEAK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 255,
    property_id: 17,
    value: 'LS 232 RED MAHOGANY (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 256,
    property_id: 17,
    value: 'LS 237 WENGE (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 257,
    property_id: 17,
    value: 'LS 862 FRENCH OAK (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139"]}',
    image_file_name: null,
  },
  {
    id: 258,
    property_id: 17,
    value: 'A600 (WHITE)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 259,
    property_id: 17,
    value: 'A103 (PERAL)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["0"]}',
    image_file_name: null,
  },
  {
    id: 260,
    property_id: 17,
    value: 'A700 (BLACK)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 261,
    property_id: 17,
    value: 'A800 (SILVER)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 262,
    property_id: 17,
    value: 'A202 (LIGHT CEDAR) (+10%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["0"]}',
    image_file_name: null,
  },
  {
    id: 263,
    property_id: 17,
    value: 'A203 (GOLDEN OAK ) (+10%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["0"]}',
    image_file_name: null,
  },
  {
    id: 264,
    property_id: 17,
    value: 'P601 PURE WHITE BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 265,
    property_id: 17,
    value: 'P603 VANILLA BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 266,
    property_id: 17,
    value: 'P630 WINTER WHITE BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 267,
    property_id: 17,
    value: 'P631 STONE BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 268,
    property_id: 17,
    value: 'P632 MISTRAL BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 269,
    property_id: 17,
    value: 'LS615 CLASSICAL WHITE BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 270,
    property_id: 17,
    value: 'P910 JET BLACK BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 271,
    property_id: 17,
    value: 'P817 OLD TEAK BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 272,
    property_id: 17,
    value: 'P819 COFFEE BEAN BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 273,
    property_id: 17,
    value: 'PS-1 HONEY BRUSHED (+20%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138"]}',
    image_file_name: null,
  },
  {
    id: 274,
    property_id: 17,
    value: 'A200 (BLACK WALNUT) (+10%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["0"]}',
    image_file_name: null,
  },
  {
    id: 293,
    property_id: 17,
    value: 'UK01 White',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["292"]}',
    image_file_name: null,
  },
  {
    id: 32,
    property_id: 7,
    value: 'Bay Window',
    code: 'bay',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","188"]}',
    image_file_name: 'Bay_Window.png',
  },
  {
    id: 146,
    property_id: 7,
    value: 'Bay Window Tier-on-Tier',
    code: 'bay-tot',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","188"]}',
    image_file_name: 'thumb_Bay_Window.png',
  },
  {
    id: 30,
    property_id: 7,
    value: 'Café Style',
    code: 'cafe',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","188"]}',
    image_file_name: 'Cafe_Style.png',
  },
  {
    id: 225,
    property_id: 7,
    value: 'Café Style Bay Window',
    code: 'cafe-bay',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","188"]}',
    image_file_name: 'Bay_Window_Cafe_Style.png',
  },
  {
    id: 36,
    property_id: 7,
    value: 'Arched Shaped',
    code: 'shaped',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","188"]}',
    image_file_name: 'Special-Shape.png',
  },
  {
    id: 42,
    property_id: 7,
    value: 'Solid Arched Shaped',
    code: 'shaped',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Special-Shape.png',
  },
  {
    id: 33,
    property_id: 7,
    value: 'Special Shaped',
    code: 'shaped',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","188","187"]}',
    image_file_name: 'Special-Shape.png',
  },
  {
    id: 43,
    property_id: 7,
    value: 'Solid Special Shaped',
    code: 'shaped',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Special-Shape.png',
  },
  {
    id: 34,
    property_id: 7,
    value: 'French Door Cut',
    code: 'french',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: 'French-Door-Cut.png',
  },
  {
    id: 221,
    property_id: 7,
    value: 'Solid Flat Panel',
    code: 'solid-flat',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Solid_Flat_Panel.png',
  },
  {
    id: 227,
    property_id: 7,
    value: 'Solid Flat<br/>Tier-on-Tier',
    code: 'solid-flat-tot',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Solid_Panel_Tier_on_Tier_Flat_bcf18cd5d2.png',
  },
  {
    id: 226,
    property_id: 7,
    value: 'Solid Raised Café Style',
    code: 'solid-raised-cafe-style',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Solid-Raised-Panel-Cafe-Style.png',
  },
  {
    id: 222,
    property_id: 7,
    value: 'Solid Raised<br/>Panel',
    code: 'solid-raised',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Solid_Raised_Panels.png',
  },
  {
    id: 228,
    property_id: 7,
    value: 'Solid Raised<br/>Tier-on-Tier',
    code: 'solid-raised-tot',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Solid_Panel_Tier_on_Tier_Raised_6ced5183ab.png',
  },
  {
    id: 229,
    property_id: 7,
    value: 'Solid Combi Panel',
    code: 'solid-combi',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'combi-panel.jpg',
  },
  {
    id: 230,
    property_id: 7,
    value: 'Solid Panel Bay Window Full Height',
    code: 'solid-flat',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'combi-panel.jpg',
  },
  {
    id: 231,
    property_id: 7,
    value: 'Solid Panel Bay Window Tier-on-Tier',
    code: 'solid-flat-tot',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'combi-panel.jpg',
  },
  {
    id: 232,
    property_id: 7,
    value: 'Solid Panel Bay Window Cafe Style',
    code: 'solid-raised-cafe-style',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'combi-panel.jpg',
  },
  {
    id: 233,
    property_id: 7,
    value: 'Solid Combi Panel Bay Window',
    code: 'solid-combi',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'combi-panel.jpg',
  },
  {
    id: 31,
    property_id: 7,
    value: 'Tier-on-Tier',
    code: 'tot',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5","187","188"]}',
    image_file_name: 'Tier-on-Tier.png',
  },
  {
    id: 35,
    property_id: 7,
    value: 'Tracked',
    code: 'tracked',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","188"]}',
    image_file_name: 'Tracked.png',
  },
  {
    id: 37,
    property_id: 7,
    value: 'Tracked',
    code: 'tracked',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187","139","147","138","6","137","5","188"]}',
    image_file_name: 'Tracked.png',
  },
  {
    id: 38,
    property_id: 7,
    value: 'Tracked',
    code: 'tracked',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Tracked.png',
  },
  {
    id: 39,
    property_id: 7,
    value: 'Tracked',
    code: 'tracked',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Tracked.png',
  },
  {
    id: 40,
    property_id: 7,
    value: 'Tracked',
    code: 'tracked',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Tracked.png',
  },
  {
    id: 41,
    property_id: 7,
    value: 'Tracked',
    code: 'tracked',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","138","137","5"]}',
    image_file_name: 'Tracked.png',
  },
  {
    id: 289,
    property_id: 10,
    value: 'P4023B',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4023B.png',
  },
  {
    id: 300,
    property_id: 10,
    value: 'A4001',
    code: 'L50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: 'A4001A.png',
  },
  {
    id: 301,
    property_id: 10,
    value: 'A4002',
    code: 'Z50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: 'A4028.png',
  },
  {
    id: 305,
    property_id: 10,
    value: '4001A',
    code: 'L50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4001A.png',
  },
  {
    id: 306,
    property_id: 10,
    value: '4007A',
    code: 'L70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4007A.png',
  },
  {
    id: 307,
    property_id: 10,
    value: '4008A',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4008A.png',
  },
  {
    id: 308,
    property_id: 10,
    value: '4001B',
    code: 'L70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4001B.png',
  },
  {
    id: 290,
    property_id: 10,
    value: '4011B',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4011B.png',
  },
  {
    id: 309,
    property_id: 10,
    value: '4007B',
    code: 'L90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4007B.png',
  },
  {
    id: 310,
    property_id: 10,
    value: '4008B',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4008B.png',
  },
  {
    id: 311,
    property_id: 10,
    value: '4001C',
    code: 'L70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4001C.png',
  },
  {
    id: 312,
    property_id: 10,
    value: '4007C',
    code: 'L90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4007C.png',
  },
  {
    id: 313,
    property_id: 10,
    value: '4008C',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '40078C.png',
  },
  {
    id: 420,
    property_id: 10,
    value: '4108C',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '40078C.png',
  },
  {
    id: 314,
    property_id: 10,
    value: '4003',
    code: 'Z40',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4003.png',
  },
  {
    id: 315,
    property_id: 10,
    value: '4004',
    code: 'Z3CS',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4004.png',
  },
  {
    id: 320,
    property_id: 10,
    value: 'P4001N',
    code: 'L50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4001N.png',
  },
  {
    id: 321,
    property_id: 10,
    value: 'P4008H',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008H.png',
  },
  {
    id: 322,
    property_id: 10,
    value: 'P4008T',
    code: 'F90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008T.png',
  },
  {
    id: 318,
    property_id: 10,
    value: 'P4028B',
    code: 'F90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008T.png',
  },
  {
    id: 319,
    property_id: 10,
    value: 'P4008W',
    code: 'F90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008T.png',
  },
  {
    id: 330,
    property_id: 10,
    value: 'P4008S',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008S.png',
  },
  {
    id: 331,
    property_id: 10,
    value: 'P4007A',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4007A.png',
  },
  {
    id: 332,
    property_id: 10,
    value: '4022B',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4022B.png',
  },
  {
    id: 351,
    property_id: 10,
    value: 'P4022B',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4022B.png',
  },
  {
    id: 142,
    property_id: 10,
    value: '4009',
    code: 'D50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4009.png',
  },
  {
    id: 316,
    property_id: 10,
    value: '4013',
    code: 'Z50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4013.png',
  },
  {
    id: 317,
    property_id: 10,
    value: '4014',
    code: 'Z50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4014.png',
  },
  {
    id: 352,
    property_id: 10,
    value: '4024',
    code: 'F90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4024.png',
  },
  {
    id: 353,
    property_id: 10,
    value: '4008T',
    code: 'F90',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4008T.png',
  },
  {
    id: 333,
    property_id: 10,
    value: '4028B',
    code: 'F70',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: '4028B.png',
  },
  {
    id: 323,
    property_id: 10,
    value: 'P4008K',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008K.png',
  },
  {
    id: 324,
    property_id: 10,
    value: 'P4073',
    code: 'Z50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4073.png',
  },
  {
    id: 325,
    property_id: 10,
    value: 'P4013',
    code: 'Z40',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4013.png',
  },
  {
    id: 326,
    property_id: 10,
    value: 'P4023',
    code: 'Z2BS',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4023.png',
  },
  {
    id: 327,
    property_id: 10,
    value: 'P4033',
    code: 'Z50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4033.png',
  },
  {
    id: 328,
    property_id: 10,
    value: 'P4043',
    code: 'Z40',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4043.png',
  },
  {
    id: 329,
    property_id: 10,
    value: 'P4014',
    code: 'Z3CS',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4014.png',
  },
  {
    id: 303,
    property_id: 10,
    value: 'P4009',
    code: 'Z3CS',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4014.png',
  },
  {
    id: 421,
    property_id: 10,
    value: 'P4019',
    code: 'Z3CS',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4014.png',
  },
  {
    id: 350,
    property_id: 19,
    value: '60mm A1002D (Std.beaded stile)',
    code: 'FS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 354,
    property_id: 19,
    value: '60mm A1006D (beaded D-mould)',
    code: 'FS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 355,
    property_id: 19,
    value: '51mm 1001B( plain butt)',
    code: 'FS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 356,
    property_id: 19,
    value: '51mm 1005B(plain D-mould',
    code: 'DFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 357,
    property_id: 19,
    value: '51mm 1002B(beaded butt)',
    code: 'BS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 358,
    property_id: 19,
    value: '51mm 1006B(beaded D-mould)',
    code: 'DBS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 359,
    property_id: 19,
    value: '51mm 1004B(beaded rebate)',
    code: 'RBS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 360,
    property_id: 19,
    value: '51mm 1003B(plain rebate)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 361,
    property_id: 19,
    value: '35mm 1001A(plain butt)',
    code: 'FS 38.1',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 362,
    property_id: 19,
    value: '35mm 1005A(plain D-mould)',
    code: 'DFS 38.1',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 363,
    property_id: 19,
    value: '35mm 1002A(beaded butt)',
    code: 'BS 38.1',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 364,
    property_id: 19,
    value: '35mm 1006A(beaded D-mould)',
    code: 'DBS 38.1',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 365,
    property_id: 19,
    value: '35mm 1004A(beaded rebate)',
    code: 'RBS 38.1',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 366,
    property_id: 19,
    value: '35mm 1003A(plain rebate)',
    code: 'RFS 38.1',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147"]}',
    image_file_name: null,
  },
  {
    id: 370,
    property_id: 19,
    value: '51mm T1001K(plain butt)',
    code: 'FS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 371,
    property_id: 19,
    value: '51mm T1005K(plain D-mould)',
    code: 'DFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 372,
    property_id: 19,
    value: '51mm T1002K(beaded butt)',
    code: 'BS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 373,
    property_id: 19,
    value: '51mm T1006K(beaded D-mould)',
    code: 'DBS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 374,
    property_id: 19,
    value: '51mm T1004K(beaded rebate)',
    code: 'RBS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","143","144"]}',
    image_file_name: null,
  },
  {
    id: 375,
    property_id: 19,
    value: '51mm T1003K(plain rebate)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 376,
    property_id: 19,
    value: '41mm T1001M(plain butt)',
    code: 'FS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147","6"]}',
    image_file_name: null,
  },
  {
    id: 377,
    property_id: 19,
    value: '41mm T1005M(plain D-mould)',
    code: 'DFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147","6"]}',
    image_file_name: null,
  },
  {
    id: 378,
    property_id: 19,
    value: '41mm T1003M(plain rebate)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147","6"]}',
    image_file_name: null,
  },
  {
    id: 380,
    property_id: 19,
    value: '51mm PVC-P1001B(plain butt)',
    code: 'FS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 381,
    property_id: 19,
    value: '51mm PVC-P1005B(plain D-mould)',
    code: 'DFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 382,
    property_id: 19,
    value: '51mm PVC-P1002B(beaded butt)',
    code: 'BS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 383,
    property_id: 19,
    value: '51mm PVC-P1006B(beaded D-mould)',
    code: 'DBS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 384,
    property_id: 19,
    value: '51mm PVC-P1004E(beaded rebate)',
    code: 'RBS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 385,
    property_id: 19,
    value: '51mm PVC-P1003E(plain rebate)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","188"]}',
    image_file_name: null,
  },
  {
    id: 400,
    property_id: 16,
    value: 'Centre Rod',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","139","147"]}',
    image_file_name: null,
  },
  {
    id: 402,
    property_id: 16,
    value: 'Offset Rod',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: null,
  },
  {
    id: 387,
    property_id: 16,
    value: 'Hidden Tilt with Louver Lock',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 401,
    property_id: 16,
    value: 'Hidden tilt',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","139","147","187"]}',
    image_file_name: null,
  },
  {
    id: 388,
    property_id: 16,
    value: 'Fixed Louvers',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 403,
    property_id: 16,
    value: 'Concealed tilt(+5%)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6","137","5"]}',
    image_file_name: null,
  },
  {
    id: 437,
    property_id: 22,
    value: 'P7032 - Standard T-Post',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","137","5"]}',
    image_file_name: null,
  },
  {
    id: 438,
    property_id: 22,
    value: '7001 - Basswood std. T-Post',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6"]}',
    image_file_name: null,
  },
  {
    id: 439,
    property_id: 22,
    value: '7201 - T-Post with insert',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6"]}',
    image_file_name: null,
  },
  {
    id: 441,
    property_id: 22,
    value: '7011 - Large T-Post',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["139","147","138","6"]}',
    image_file_name: null,
  },
  {
    id: 442,
    property_id: 22,
    value: 'A7001',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 443,
    property_id: 22,
    value: 'T7032',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 444,
    property_id: 22,
    value: 'P7030',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6","137","5"]}',
    image_file_name: null,
  },
  {
    id: 445,
    property_id: 19,
    value: '41mm T1002M(beaded butt)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 446,
    property_id: 19,
    value: '41mm T1004M(beaded rebate)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 447,
    property_id: 19,
    value: '41mm T1006M(beaded D-mould)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","6"]}',
    image_file_name: null,
  },
  {
    id: 457,
    property_id: 17,
    value: 'A400 (Surfmist)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 456,
    property_id: 17,
    value: 'A500 (Antracit)',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 458,
    property_id: 15,
    value: 'Earth hinge',
    code: '',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["187"]}',
    image_file_name: null,
  },
  {
    id: 459,
    property_id: 19,
    value: '41mm 1002M(beaded butt)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: null,
  },
  {
    id: 460,
    property_id: 19,
    value: '41mm 1004M(beaded butt)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: null,
  },
  {
    id: 461,
    property_id: 19,
    value: '41mm 1006M(beaded butt)',
    code: 'RFS 50.8',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["138","139","147"]}',
    image_file_name: null,
  },
  {
    id: 462,
    property_id: 10,
    value: 'P4008R',
    code: 'F50',
    all_products: true,
    selected_products: '{"product_ids":null}',
    all_property_values: false,
    selected_property_values: '{"property_field":"18","property_value_ids":["137","5","138","6","188","147"]}',
    image_file_name: 'P4008K.png',
  },
];

var property_fields = [
  { id: 7, code: 'style' },
  { id: 8, code: 'bladesize' },
  { id: 9, code: 'fit' },
  { id: 10, code: 'frametype' },
  { id: 11, code: 'frameleft' },
  { id: 12, code: 'frameright' },
  { id: 13, code: 'frametop' },
  { id: 14, code: 'framebottom' },
  { id: 15, code: 'hingecolour' },
  { id: 16, code: 'controltype' },
  { id: 17, code: 'shuttercolour' },
  { id: 18, code: 'material' },
  { id: 19, code: 'stile' },
  { id: 20, code: 'midrailpositioncritical' },
  { id: 21, code: 'locks' },
  { id: 22, code: 'tposttype' },
];
